site_name: Satchel Documentation
site_url: https://ryanluu.dev/Satchel

repo_name: RyanLua/Satchel
repo_url: https://github.com/RyanLua/Satchel

theme:
  name: material
  language: en
  # logo: https://raw.githubusercontent.com/RyanLua/Satchel/main/assets/IconOn.png
  # favicon: https://raw.githubusercontent.com/RyanLua/Satchel/main/assets/IconOn.png
  features:
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: light blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: light blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Guide:
    - Installation: installation.md
    - Usage: usage.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox