name: Report a bug
description: File a bug report.
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Write a brief sentence about the bug
      value: __What is the bug and what does it do?__
  - type: textarea
    id: expected-behavior
    attributes:
      label: What was expected?
      description: What did you expect to happen?
      placeholder: When I do this, that is supposed to happen
      value: __What do you expect to see?__
  - type: textarea
    id: actual-behavior
    attributes:
      label: What actually happened?
      description: What happened instead?
      placeholder: When I do this, it instead does that.
      value: __What actually happened?__
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
      value: |
        1. __Show the steps to reproduce the issue__
        2. __Make sure they are numbered__
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      placeholder: |
        Add any relevant log output here. This includes any errors or warnings.
      value: __Any outputs or logs of when the bug occurred?__
  - type: textarea
    id: other-details
    attributes:
      label: Other details
      description: |
        Anything else you would like to add?
        (screenshots, links, videos, etc.)
      placeholder: |
        Any other details you would like to add? You can attach files here, this includes screenshots, videos, etc.
      value: __Do you have any pictures or videos of the bug? If so, provide them.__
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Moderate
        - High
        - Critical
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms affected
      multiple: true
      options:
        - Computer
        - Tablet
        - Phone
        - Console
        - VR
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: This project has a Code of Conduct that all participants are expected to understand and follow.
      options:
        - label: I have read and agree to the project's [Code of Conduct](../blob/main/CODE_OF_CONDUCT.md)
          required: true
