blank_issues_enabled: true
contact_links:
  - name: Get Community Support
    url: https://github.com/RyanLua/Satchel/discussions
    about: Get support/help from the GitHub Discussions community.
  - name: Email us
    url: mailto:support@ryanluu.dev
    about: Send us a email
