name: CI

on:
  pull_request:
    paths-ignore:
      - "**"
      - "!.github/workflows/ci.ya?ml"
      - "!**.lua"

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/ci.ya?ml"
      - "!**.lua"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Selene
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          cache: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Selene
        run: selene src
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check src
