name: Continuous Integration

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/ci.ya?ml"
      - "!**.luau"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Selene
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Run Selene
        run: selene src

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check src
