name: Check Markdown

on:
  workflow_dispatch:

  push:
    paths-ignore:
      - "**"
      - "!.github/workflows/markdown.ya?ml"
      - "!**.md"

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          fix: true
          globs: "**/*.md"
