name: Release

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Wally
        env:
          WALLY_AUTH_TOKEN: ${{ secrets.WALLY_AUTH_TOKEN }}
        run: |
          wally login --token "$WALLY_AUTH_TOKEN"
          wally install

      - name: Build using Rojo
        run: |
          mkdir builds
          rojo build --output builds/Satchel.rbxm default.project.json
          rojo build --output builds/Satchel.rbxmx default.project.json

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: builds/

      - name: Publish to Wally
        run: wally publish

      - name: Archive build files
        uses: actions/upload-artifact@v4
        with:
          name: release-file-builds
          path: builds/
          if-no-files-found: error
          compression-level: 9